name: padi4life
description: Hackatone FCMB
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_adjust: ^0.0.2
  flutter_hooks: ^0.18.6
  google_fonts: ^5.0.0
  gap: ^3.0.1
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.1
  dio: ^5.3.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_overlay_loader: ^2.0.0
  dartz: ^0.10.1
  hooks_riverpod: ^2.3.6
  lottie: ^2.4.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svgs/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
